[PHP]
; Límites de subida y POST
upload_max_filesize = 100M
post_max_size = 100M

; Límites de ejecución y memoria
max_execution_time = 300
max_input_time = 120
memory_limit = 1024M
max_input_vars = 5000

; Asegurar que las subidas estén activas
file_uploads = On
max_file_uploads = 20





