[build]
builder = "nixpacks"

[deploy]
# La bandera -c fuerza a PHP a leer nuestro php.ini
startCommand = "php -c /app/php.ini -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/health.php"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3